language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 홈
cache: # 같은 의존성은 다음 배포 때부터 안 받는다.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build" # 브랜치 푸시시 수행하는 명령어

before_deploy:
#  - zip -r blogProject * # 현재 경로 모든 파일 압축
#  - mkdir -p deploy # 현재 travis CI가 실행중인 위치에서 생성
#  - mv blogProject.zip deploy/blogProject.zip
  - mkdir -p before-zip
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before_deploy && zip -r before-deploy
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/blogProject.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: blogproject-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: blogproject-build
    key: blogProject.zip

    bundle_type: zip
    application: blogProject

    deployment_group: blogProject-group

    region: ap-northeast-2
    wati-until-deployed: true

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - sijune0525@gmail.com