version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

permissions: # codedeploy에서 ec2로 넘어온 모든파일에 권한 부여
  - object:
      pattern: "**"
      owner: ec2-user
      group: ec2-user

hooks:
  ApplicationStart: # ec2-ussr권한으로 deploy.sh실행
    - location: deploy.sh
      timeout: 60
      runas: ec2-user